config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :cities

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/provinces', to: 'provinces#index'
  get '/provinces/:id' => 'provinces#show'

  get '/welcome', to: 'pages#welcome'

  root 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province

  validates :name, presence: { message: 'es un dato obligatorio.' }
  validates :name, length: { in: 2..250, message: 'debe ser entre 2 y 250 caracteres' }
  validates :name, uniqueness: { message: 'ya está siendo utilizado.', case_sensitive: false }

end

app/models/province.rb
class Province < ApplicationRecord
  has_many :cities

  validates :name, presence: { message: 'es un dato obligatorio.' }
  validates :name, length: { in: 2..250, message: 'debe ser entre 2 y 250 caracteres' }
  validates :name, uniqueness: { message: 'ya está siendo utilizado.', case_sensitive: false }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :phone, :address])
  end

  def after_sign_in_path_for(resource)
    if current_user.user_type == "admin"
      edit_user_registration_path(current_user)
    else
      root_path
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'Ciudad creada correctamente!.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :city_population, :province_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController

  def index
    @provinces = Province.all

    @tu_nombre = "Matias"
    @tipo_usuario = "usuario"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

        <ul>
        <% city.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre de la ciudad", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :city_population, "Población Total", class: "form-label" %>
    <%= form.number_field :city_population, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :province_id, "Cod. Provincia", class: "form-label" %>
    <%= form.text_field :province_id, class: "form-control", required: true  %>
  </div>

  <div class="form-group actions">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editando Ciudad</h1>

<%= render 'form', city: @city %>

<%= link_to 'Mostrar', @city, class: "btn btn-light" %> |
<%= link_to 'Volver', cities_path, class: "btn btn-light" %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Ciudades</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Población</th>
      <th scope="col">Provincia</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td scope="row"><%= city.id %></td>
        <td><%= city.name %></td>
        <td><%= city.city_population %></td>
        <td><%= city.province.name %></td>
        <td><%= link_to 'Mostrar', city %></td>
        <td><%= link_to 'Editar', edit_city_path(city) %></td>
        <td><%= link_to 'Eliminar', city, method: :delete, data: { confirm: '¿Esta seguro de borrar esto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva ciudad', new_city_path, class: "btn btn-outline-primary" %>

app/views/cities/new.html.erb
<h1>Nueva cidad</h1>

<%= render 'form', city: @city %>

<%= link_to 'Volver', cities_path, class: "btn btn-outline-secondary" %>

app/views/cities/show.html.erb
<div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @city.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Provincia de <%= @city.province.name %></h6>
      <p class="card-text">Tiene una población de <%= @city.city_population %></p>
    </div>
  </div>

  <br>
  <%= link_to 'Editar', edit_city_path(@city.id), class: "btn btn-light" %> |
  <%= link_to 'Volver', cities_path, class: "btn btn-light" %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>App Curso Repaso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <p class="alert"><%= notice %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>

      <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p class="alert"><%= alert %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<h1>Bienvenido/a a nuestra aplicación!!</h1>


<section>
  <h1>¿Eres usuario?</h1>
  <h2>Sub titulo</h2>
  <article> Articulo uno</article>
  <article>Articulo dos</article>
  <article>Articulo tres</article>
</section>

<section>
  <main role="main">
    <p>Sino tiene una cuenta, deberá crear una primero para poder utilizar la aplicación</p>
    <%= link_to "Crear cuenta", new_user_registration_path %><br />
    <br>
    <p>Si tiene cuenta, haga click en el siguiente enlace para identificarse</p>
    <%= link_to "Iniciar sesion", new_user_session_path %>
</main>

</section>

<% if user_signed_in? %>
  <h2>Usted ya esta indentificado</h2>
  <article>
    <p><%= current_user.name %></p>
    <p><%= current_user.user_type %></p>
  </article>
  <%= link_to "Mi Perfil", edit_user_registration_path(current_user) if current_user.id   %>
  | <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete  %>
<% else %>
  <h2>Usted NO esta indentificado</h2>
  <%= link_to "Iniciar sesion", new_user_session_path %>
<% end %>

<br>
<br>
<br>

<%= link_to "Provincias", provinces_path %> |
<%= link_to "Ciudades", cities_path %>

|

<%= link_to "San Google", 'http://google.com.ar' %>

app/views/provinces/index.html.erb
<h1>Listando Provincias</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Poblacion</th>
    <th>created_at</th>
    <th>updated_at</th>
  </tr>

  <% @provinces.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.name %></td>
      <td><%= item.total_population %></td>
      <td><%= item.created_at %></td>
      <td><%= item.updated_at %></td>
    </tr>
  <% end %>

</table>


<%= link_to "Inicio", '/' %>